import React from "react"
import Helmet from "react-helmet"
import { Header } from "../components/Menubar"
import Intro from "../components/Intro"
import Outro from "../components/Outro"
import { Divider } from "../components/Divider"
import { Paragraph } from "../components/Paragraph"
import { Link } from "../components/Link"
import { Body } from "../components/Body"
import { Heading, FauxHeading } from "../components/Heading"

const AboutPage = props => (
  <div>
    <Helmet
      title={`${props.data.site.siteMetadata.author}, ${
        props.data.aboutPageJson.title
      }`}
    />

    <Header
      author={props.data.site.siteMetadata.author}
      title={props.data.aboutPageJson.title}
    />

    <Intro bgColor={props.data.aboutPageJson.coverBgColor}>
      <img
        src={props.data.aboutPageJson.coverImage.publicURL}
        alt="Avatar"
        style={{
          verticalAlign: "middle",
          maxWidth: "65vw",
          maxHeight: "65vh",
          borderRadius: "100%"
        }}
      />
    </Intro>

    <Body>
      <Heading inBody>
        Who dis guy?{" "}
        <span role="img" aria-label="Point up emoji">
          👆
        </span>
      </Heading>

      <Paragraph>
        Though the homepage of this site says that I&rsquo;m a{" "}
        <em>designer in Amsterdam</em>, I&rsquo;m not Dutch, but I grew up in
        rural Austria surrounded by mountains… And cows. It was only a few
        coincidences later, by way of{" "}
        <Link href="https://goo.gl/maps/iRq5h9F1xuR2" target="_blank">
          Victoria
        </Link>{" "}
        and Vienna, that I ended up in the city where ice skating is an{" "}
        <Link
          href="https://mashable.com/2018/02/11/dutch-speed-skating-explanation/#Yq6b0N0exOqG"
          target="_blank"
        >
          important mode of transportation
        </Link>. I was lucky enough to get hired by the charming people of{" "}
        <Link href="https://www.bolden.nl/" target="_blank">
          Bolden
        </Link>, after I had convinced them I&rsquo;d be sort of both, designer{" "}
        <em>and</em> developer. Which is really what I like to do: Working at
        the intersection of design and technology.
      </Paragraph>

      <Paragraph>
        Doesn&rsquo;t really matter to me whether it&rsquo;s a Sketch file or a
        React component, OCD&rsquo;ing over reusability and consistency in
        either of them makes me equally happy.
      </Paragraph>

      <Paragraph>
        Send me an <Link href="mailto:hi@rppld.co">email</Link> or{" "}
        <Link
          href="https://twitter.com/messages/compose?recipient_id=16256510&text=Hi"
          target="_blank"
        >
          DM me on Twitter
        </Link>{" "}
        if you want to know more about me or discuss work opportunities.
      </Paragraph>

      <Heading inBody secondary>
        Nitty gritty about this site
      </Heading>

      <Paragraph>
        This website is all static HTML files generated by{" "}
        <Link href="https://www.gatsbyjs.org/" target="_blank">
          GatsbyJS
        </Link>, which is amazing and I absolutely love using it! It&rsquo;s
        generously hosted on{" "}
        <Link href="https://www.netlify.com/" target="_blank">
          Netlify
        </Link>&rsquo;s servers. The source code is in a{" "}
        <Link href="https://github.com/rppld/rppld.co" target="_blank">
          public repository
        </Link>{" "}
        over at GitHub in case you&rsquo;re curious. The typeface used is{" "}
        <Link href="https://www.boldmonday.com/custom/ibm/" target="_blank">
          IBM Plex
        </Link>{" "}
        by <em>Bold Monday</em>, a Dutch foundry. And I love Holland{" "}
        <span role="img" aria-label="Tulip emoji">
          🌷
        </span>
        <span role="img" aria-label="Cheese emoji">
          🧀
        </span>{" "}
        Yasss!
      </Paragraph>

      <Divider />
    </Body>

    <Outro>
      <FauxHeading>
        Thanks for sticking around and reading all this!{" "}
        <Link
          href="https://www.youtube.com/watch?v=VPtkExITE1w"
          target="_blank"
        >
          Here
        </Link>, watch a hairless cat scratch its head on a guys&rsquo; beard.
      </FauxHeading>
    </Outro>
  </div>
)

export default AboutPage

export const query = graphql`
  query AboutPageQuery {
    aboutPageJson {
      title
      coverImage {
        publicURL
      }
      coverBgColor
    }
    site {
      siteMetadata {
        author
      }
    }
  }
`
