name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cypress:
    runs-on: ubuntu-16.04
    name: E2E
    env:
      STORYBLOK_API_KEY: ${{ secrets.STORYBLOK_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn start
          browser: chrome
