name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E
    env:
      STORYBLOK_API_KEY: ${{ secrets.STORYBLOK_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          browser: chrome
